version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=my_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
    ports:
      - '5433:5432'
    volumes:
      - './postgres_data:/var/lib/postgresql/data'

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=root@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - '5051:80'
    volumes:
      - './pgadmin_data:/var/lib/pgadmin'

  mongo:
    image: mongo:5.0
    environment:
      - MONGO_ROOT_USER=mongo
      - MONGO_ROOT_PASSWORD=secreta123
      - MONGO_DB=admin
    ports:
      - '27017:27017'
    volumes:
      - 'mongodb_data:/data/db'

volumes:
  postgres_data:
  pgadmin_data:
  mongodb_data:
